server:
  port: 8007
spring:
  rabbitmq:
    host: 192.168.42.132
    username: admin
    password: admin
    port: 5672
#打开本地配置
#  profiles:
#    active: native
  application:
    name: jt-config
  redis:
    host: 192.168.42.132
    port: 6379 
  cloud:    config:      server:        git:          uri: https://github.com/wwenyi/jt-config.git
          search-paths: config          username: wwenyi
          password: wjbgnsmms123
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh